version: "3"

services:

  backend:
    image: superseriousbusiness/gotosocial:latest
    restart: unless-stopped
    user: 1000:1000
    env_file:
      - secure.env
    environment:
      # ActitivyPub
      GTS_HOST: social.ewpratten.com
      GTS_ACCOUNT_DOMAIN: ewpratten.com
      # Database
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      # HTTP
      GTS_LETSENCRYPT_ENABLED: false
      GTS_PROTOCOL: http
      GTS_TRUSTED_PROXIES: "cloudflared"
      # SMTP
      GTS_SMTP_HOST: smtp.ewpratten.com
      GTS_SMTP_PORT: 587
      GTS_SMTP_USERNAME: social@ewpratten.com
      GTS_SMTP_FROM: social@ewpratten.com
      GTS_SMTP_DISCLOSE_RECIPIENTS: true
    volumes:
      - ./data:/gotosocial/storage
    networks:
      - internal

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - secure.env
    networks:
      - internal

networks:
  internal:
