version: "3"

services:

  mastodon:
    image: lscr.io/linuxserver/mastodon:glitch
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - secure.env
    environment:
      # ActivityPub
      LOCAL_DOMAIN: ewpratten.com
      WEB_DOMAIN: social.ewpratten.com
      # Databases
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: mastodon
      DB_NAME: mastodon
      # Optional Featues
      ES_ENABLED: false
      SINGLE_USER_MODE: true
      # SMTP
      SMTP_SERVER: smtp.migadu.com
      SMTP_PORT: 587
      SMTP_LOGIN: "social@ewpratten.com"
      SMTP_FROM_ADDRESS: social@ewpratten.com
      # Object Storage
      S3_ENABLED: false
      # S3_ALIAS_HOST: social-cdn.ewpratten.com
      # S3_BUCKET: social-cdn
      # S3_ENDPOINT: https://ddc0f8101374c7bf29ab528eefc435ec.r2.cloudflarestorage.com/
      # S3_PROTOCOL: https
      # S3_PERMISSION: private

    volumes:
      - ./mastodon/config:/config
    networks:
      - internal

  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./mastodon/postgres14:/var/lib/postgresql/data
    env_file:
      - secure.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mastodon
      - POSTGRES_USER=mastodon
    networks:
      - internal

  redis:
    restart: always
    image: redis:7-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./mastodon/redis:/data
    networks:
      - internal

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - secure.env
    networks:
      - internal

networks:
  internal:
