version: "3"

services:

  web:
    image: jointakahe/takahe
    restart: unless-stopped
    env_file:
      - secure.env
      - common.env
    volumes:
      - ./media:/data/media
    depends_on:
      - database
    networks:
      - internal

  worker:
    image: jointakahe/takahe
    restart: unless-stopped
    env_file:
      - secure.env
      - common.env
    volumes:
      - ./media:/data/media
    command: python3 manage.py runstator
    depends_on:
      - database
    networks:
      - internal

  media_cdn:
    image: sebp/lighttpd
    restart: unless-stopped
    volumes:
      - ./media:/var/www/media
      - ./config/lighttpd.conf:/etc/lighttpd/lighttpd.conf
    tty: true
    networks:
      - internal

  database:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    env_file:
      - secure.env
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=takahe
      - POSTGRES_DB=takahe
    networks:
      - internal

  setup:
    image: jointakahe/takahe
    restart: "no"
    env_file:
      - secure.env
      - common.env
    volumes:
      - ./media:/data/media
    depends_on:
      - database
    networks:
      - internal
    command: bash -c "/takahe/manage.py migrate && /takahe/manage.py collectstatic --noinput"

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - secure.env
    networks:
      - internal

networks:
  internal:
